ignore missing file exceptions while deleting old instance files
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in org.apache.activemq.artemis.arquillian.replicated6node.ReplicatedFailbackTest
[ERROR] checkFailback(org.apache.activemq.artemis.arquillian.replicated6node.ReplicatedFailbackTest)  Time elapsed: 0.004 s  <<< ERROR!
java.lang.IllegalStateException: unable to start broker2
Caused by: java.nio.file.NoSuchFileException: ./target/live1/tmp/jetty-localhost-8161-artemis-plugin.war-_artemis-plugin-any-4710008422643815530.dir/webapp/plugin/lib